using System.Collections.Generic;
using UnityEngine;

namespace RhythmRunner.Platforme.MapWorkshop
{
    // Global feasibility utilities for maps generated by the workshop
    public static class FeasibilityChecker
    {
        // Path exists given a boolean grid where true = obstacle
        public static bool PathExists(bool[,] grid)
        {
            int w = grid.GetLength(0);
            int h = grid.GetLength(1);
            if (w <= 0 || h <= 0) return false;

            bool[,] visited = new bool[w, h];
            var q = new System.Collections.Generic.Queue<Vector2Int>();

            // Start from any open cell on the left edge
            for (int y = 0; y < h; y++)
            {
                if (!grid[0, y]) { q.Enqueue(new Vector2Int(0, y)); visited[0, y] = true; }
            }

            int[] dx = new int[] { 1, -1, 0, 0 };
            int[] dy = new int[] { 0, 0, 1, -1 };

            while (q.Count > 0)
            {
                var cur = q.Dequeue();
                if (cur.x == w - 1) return true; // reached right edge
                for (int d = 0; d < 4; d++)
                {
                    int nx = cur.x + dx[d];
                    int ny = cur.y + dy[d];
                    if (nx >= 0 && nx < w && ny >= 0 && ny < h && !grid[nx, ny] && !visited[nx, ny])
                    {
                        visited[nx, ny] = true;
                        q.Enqueue(new Vector2Int(nx, ny));
                    }
                }
            }
            return false;
        }

        // Check feasibility of current map in the scene by sampling obstacles' positions
        public static bool CheckCurrentMapFeasibility(Transform mapRoot, int gridWidth, int gridHeight, float cellWidth, float cellHeight, float startX)
        {
            if (mapRoot == null) return false;
            bool[,] grid = new bool[gridWidth, gridHeight];
            foreach (Transform child in mapRoot)
            {
                if (child == mapRoot) continue;
                if (!child.gameObject.activeSelf) continue;
                Vector3 p = child.localPosition;
                int col = Mathf.RoundToInt((p.x - startX) / cellWidth);
                int row = Mathf.RoundToInt(p.y / cellHeight);
                if (col >= 0 && col < gridWidth && row >= 0 && row < gridHeight)
                {
                    grid[col, row] = true;
                }
            }
            return PathExists(grid);
        }
    }
}
